-- 
-- Data Analysis of Cab Booking Systems Project
-- Author: Praveen Kumar S
-- 

-- 
-- Schema and objects creation
-- 

/*
create database p_cab_booking;
use p_cab_booking;

CREATE TABLE Customers (
    CustomerID VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(15),
    Gender CHAR(1),
    JoinDate DATE
);

CREATE TABLE Drivers (
    DriverID VARCHAR(10) PRIMARY KEY,
    Name VARCHAR(50),
    Phone VARCHAR(15),
    LicenseNo VARCHAR(20),
    Rating DECIMAL(2,1),
    JoinDate DATE
);
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE Cabs (
    CabID VARCHAR(10) PRIMARY KEY,
    DriverID VARCHAR(10),
    CabModel VARCHAR(50),
    CabNumber VARCHAR(15),
    Capacity INT,
    Type VARCHAR(20),
    FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID)
);

CREATE TABLE Bookings (
    BookingID VARCHAR(10) PRIMARY KEY,
    CustomerID VARCHAR(10),
    CabID VARCHAR(10),
    DriverID VARCHAR(10),
    BookingDate DATE,
    PickupLocation VARCHAR(50),
    DropLocation VARCHAR(50),
    Status VARCHAR(20),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (CabID) REFERENCES Cabs(CabID),
    FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID)
);

CREATE TABLE TripDetails (
    TripID VARCHAR(10) PRIMARY KEY,
    BookingID VARCHAR(10),
    DistanceKm DECIMAL(5,1),
    DurationMins INT,
    Fare DECIMAL(8,2),
    PaymentMode VARCHAR(20),
    FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID)
);


CREATE TABLE Feedback (
    FeedbackID VARCHAR(10) PRIMARY KEY,
    BookingID VARCHAR(10),
    CustomerID VARCHAR(10),
    DriverID VARCHAR(10),
    Rating INT,
    Comments VARCHAR(100),
    FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    FOREIGN KEY (DriverID) REFERENCES Drivers(DriverID)
);
SET FOREIGN_KEY_CHECKS = 1;

show tables;

select * from Customers;
select * from cabs;
select * from Drivers;
select * from bookings;
select * from tripdetails;
select * from feedback;
*/

--
-- Customer and Booking Analysis
--
use p_cab_booking;

-- 1. Identify customers who have completed the most bookings. 
-- What insights can you draw about their behavior?
select c.customerid, c.name, count(b.bookingid) as TotalCompleteBookings from customers c inner join bookings b 
on c.customerid=b.customerid where b.status = 'completed'
group by c.customerid, c.name order by  TotalCompleteBookings desc, c.customerid;

-- 2. Find customers who have canceled more than 30% of their total bookings. 
-- What could be the reason for frequent cancellations?
select c.customerid, c.name
, count(b.bookingid) as TotalBookings
, sum(case when b.status ='cancelled' then 1 else 0 end) as CancelledBookings 
, Round((sum(case when b.status ='cancelled' then 1 else 0 end)/count(b.bookingid)) *100) as CancelRate
from customers c inner join bookings b 
on c.customerid=b.customerid 
group by c.customerid, c.name 
having CancelRate > 30;

-- 3. Determine the busiest day of the week for bookings. 
-- How can the company optimize cab availability on peak days?
select dayname(b.bookingdate) as DayName,count(*) as TotalBookings  from bookings b 
group by DayName
order by TotalBookings desc limit 1;

-- 
-- Driver Performance & Efficiency
-- 
use p_cab_booking;

-- 1. Identify drivers who have received an average rating below 3.0 in the past three months. 
-- What strategies can be implemented to improve their performance?
select d.driverid,d.name, round(avg(f.rating),2) as AvgRating  
from feedback f inner join drivers d on f.driverid=d.driverid  
inner join bookings b on f.bookingid=b.bookingid
where b.bookingdate >= date_sub(now(),interval 3 month)
group by d.driverid, d.name  
having AvgRating <= 3.0
order by AvgRating;

-- 2. Find the top 5 drivers who have completed the longest trips in terms of distance. 
-- What does this say about their working patterns?
select d.driverid,d.name,max(t.distancekm ) as distancekm
from tripdetails t inner join bookings b on t.bookingid=b.bookingid
inner join drivers d on b.driverid=d.driverid
group by d.driverid, d.name  
order by t.distancekm desc limit 5;

-- 3. Identify drivers with a high percentage of canceled trips. 
-- Could this indicate driver unreliability?
select d.driverid,d.name
,count(b.bookingid) as TotalTrips
,SUM(case when b.status='Cancelled' then 1 else 0 end) as CancelledTrips
,(SUM(case when b.status='Cancelled' then 1 else 0 end)/count(b.bookingid))*100 as CancelRate
 from drivers d inner join bookings b on d.driverid=b.driverid
group by d.driverid,d.name
having CancelRate > 30
order by CancelledTrips desc,CancelRate desc;

-- 
-- Revenue & Business Metrics
-- 
use p_cab_booking;

-- 1.Calculate the total revenue generated by completed bookings in the last 6 months. 
-- How has the revenue trend changed over time?
select sum(t.fare) as TotalRevenue from bookings b inner join tripdetails t on b.bookingid=t.bookingid 
where b.status='completed' 
and b.bookingdate >= date_sub(curdate(),interval 6 month);
 
 -- 2. Identify the top 3 most frequently traveled routes based on PickupLocation and DropoffLocation. 
 -- Should the company allocate more cabs to these routes?
 select b.pickuplocation,b.droplocation,count(*) as NumberofBookings from bookings b
 where b.status='completed'
 group by b.pickuplocation,b.droplocation
 order by NumberofBookings desc
 limit 3;
 
 -- 3. Determine if higher-rated drivers tend to complete more trips and earn higher fares. 
 -- Is there a direct correlation between driver ratings and earnings?
select d.driverid,d.name
,AVG(f.rating) AvgDriverRating
,count(b.bookingid) as TotalBookingsCompleted
,sum(t.fare) as TotalEarnings
 from drivers d 
inner join bookings b on d.driverid=b.driverid
inner join tripdetails t on b.bookingid=t.bookingid
left join feedback f on b.driverid=f.driverid
where b.status='completed'
group by d.driverid,d.name
order by AvgDriverRating desc;

-- 
-- Operational Efficiency & Optimization
-- 
use p_cab_booking;

-- 1. Analyze the average waiting time (difference between booking time and trip start time) for different pickup locations. 
-- How can this be optimized to reduce delays?
select b.pickuplocation, count(*) as TotalTrips , avg(Waitdurationmins) as AvgWaitDurationMins 
from bookings b inner join tripdetails t on b.bookingid=t.bookingid
group by b.pickuplocation
order by AvgWaitDurationMins desc;

-- 2. Identify the most common reasons for trip cancellations from customer feedback. 
-- What actions can be taken to reduce cancellations?
select f.comments,count(b.bookingid) as NumberofCancellations  
from bookings b inner join feedback f on b.bookingid=f.bookingid
where b.status='cancelled'
group by f.comments 
order by NumberofCancellations;

-- 3. Find out whether shorter trips (low-distance) contribute significantly to revenue. 
-- Should the company encourage more short-distance rides?
select case when t.distancekm <= 6 then 'Short (<=6 KM)' 
			when t.distancekm <=10 then 'Medium (6-10 KM)' 
            else 'Long (>10 KM)'
            end as TripCategory
,count(*) as TotalTrips            
,sum(fare) as TotalRevenue
,round(sum(fare)/(select sum(t2.fare) from bookings b2 inner join tripdetails t2 on b2.bookingid=t2.bookingid)*100,2)
as RevenuePercent
from tripdetails t inner join bookings b on t.bookingid=b.bookingid
where b.status='completed'
group by TripCategory
order by TotalRevenue desc;

-- 
-- Comparative & Predictive Analysis
-- 
use p_cab_booking;

-- 1. Compare the revenue generated from 'Sedan' and 'SUV' cabs. 
-- Should the company invest more in a particular vehicle type?
select C.type as VehicleType,sum(t.fare) as TotalRevenue from bookings b 
inner join tripdetails t on b.bookingid=t.bookingid
inner join cabs c on b.driverid=c.driverid
group by c.Type
order by TotalRevenue desc;

-- 2. Predict which customers are likely to stop using the service based on their last booking date and frequency of rides. 
-- How can customer retention be improved?
select c.customerid,c.name,max(b.bookingdate) as LastBookingDate,count(b.bookingid) as frequency
,datediff(curdate(),max(b.bookingdate)) as DaysSinceLastBooking
 from customers c inner join bookings b on c.customerid=b.customerid
group by c.customerid,c.name
order by DaysSinceLastBooking desc;

-- 3. Analyze whether weekend bookings differ significantly from weekday bookings. 
-- Should the company introduce dynamic pricing based on demand?
Select case when dayname(b.bookingdate) in ('Saturday','Sunday') then 'Weekend' else 'Weekday' end as DayType
, count(b.bookingid) as Totalbookings  
,sum(t.fare) as TotalRevenue
,round(Avg(t.fare),2) as AvgRevenue
-- ,dayname(b.bookingdate) as Day_Name
from bookings b inner join Tripdetails t on b.bookingid=t.bookingid
where b.status='completed'
-- group by Day_Name 
group by DayType
order by Totalbookings desc;

